- name: play level variables
  hosts: local
  coonnection: local # Ansible is connecting to localhost
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    Trainer: Sivakumar Reddy
  tasks:
  - name: print the course info
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"
