- name: Variables from files
  hosts: local
  connection: local
  taskes:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"